#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}flake8 taggy tests
${PREFIX}isort taggy tests --recursive --check-only
${PREFIX}mypy taggy tests --ignore-missing-imports
