#!/bin/sh -e

export PREFIX=""
if [ -d 'env' ] ; then
    export PREFIX="env/bin/"
fi

export VERSION=`${PREFIX}python setup.py --version`

if ! command -v "${PREFIX}twine" &>/dev/null ; then
    echo "Unable to find the 'twine' command."
    echo "Install from PyPI, using '${PREFIX}pip install twine'."
    exit 1
fi

find taggy -type f -name "*.py[co]" -delete
find taggy -type d -name __pycache__ -delete

${PREFIX}python setup.py sdist
${PREFIX}twine upload dist/*

rm -rf dist
rm -rf taggy.egg-info
